apiVersion: apps/v1
kind: Deployment
metadata:
  name: spaceman
  labels:
    app: spaceman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spaceman
  template:
    metadata:
      labels:
        app: spaceman
    spec:
      serviceAccountName: spaceman
      containers:
      - name: main
        image: fassmus/spaceman-game:v1.0.0
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: '0.5'
            memory: 256Gi
          requests:
            cpu: '0.1'
            memory: 128Mi
        volumeMounts:
          - name: spaceman
            subPath: nginx.conf
            mountPath: /etc/nginx/nginx.conf
      volumes:
        - name: spaceman
          configMap:
            name: spaceman

