apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- service-account.yaml
- role.yaml
- role-binding.yaml

configMapGenerator:
- name: spaceman
  files:
  - config-files/nginx.conf
