apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- service-account.yaml
- role.yaml
- role-binding.yaml

configMapGenerator:
- name: spaceman
  files:
  - config-files/nginx.conf

vars:
- name: CM_NAME
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: spaceman
  fieldref:
    fieldpath: metadata.name

configurations:
- kustomizeconfig/varreference.yaml